### ISSUE TITLE
Label & TextraLabel feature parity request: [] sets the color to the previous color 

### ISSUE THREAD

**Issue by lucas-kakele** [tommyettinger/textratypist#12]
Hi!

A current behavior of `TextraLabel` that does not match `Label` is the use of `[]`. 

That syntax in `Label` will sets the color to the previous color defined in the label. That syntax in `TextraLabel` will reset the color to the label original color instead.

Example:

![image](https://github.com/tommyettinger/textratypist/assets/56004737/60ea01a3-a368-4023-be2c-501bf597069a)

Code:

```
public class MyGdxGame extends ApplicationAdapter {

  private Stage stage;
  private Skin skin;

  @Override
  public void create () {
    stage = new Stage(new ScreenViewport());

    skin = new Skin(Gdx.files.internal("uiskin.json"));

    Label label = new Label("[RED]test [GREEN]test[] test[]", skin);
    label.getStyle().font.getData().markupEnabled = true;

    TextraLabel textraLabel = new TextraLabel("[red]test [green]test[] test[]", skin);

    Table table = new Table();
    table.add(label).row();
    table.add(textraLabel).row();

    Stack stack = new Stack(table);
    stack.setFillParent(true);

    stage.addActor(stack);
  }

  @Override
  public void render () {
    ScreenUtils.clear(0, 0, 0, 1);
    stage.act();
    stage.draw();
  }

  @Override
  public void dispose () {
    stage.dispose();
    skin.dispose();
  }
}
```

The request of this issue is to make `TextraLabel`'s `[]` tag match the behavior of `Label`.

Thanks!

**Comment by tommyettinger** [comment]
The main issue here is that `[]` also currently resets styles, such as bold and oblique. Should `[]` just reset the previous color, or should it rest the previous "thing in square brackets"?

**Comment by lucas-kakele** [comment]
Hi Tommy!

I think we can separate the styles applied by square brackets in two categories:

- toggle styles. eg: bold/italic can only be toggled on and off. there is no stacking
- stacking styles. eg color and size can be stacked (eg: "[%200]this [%300]is[] a test[]" or "[red]this [green]is[] a test[]")

`[]` could be used to toggle off styles that are toggled and to reset to the previous state (a stack pop) for stacking styles.

What do you think?

**Comment by tommyettinger** [comment]
Currently what I have implemented just records whenever there's a change to the color/style/size/font-family state, and using `[]` should (soon?) drop back one step in the history. Getting this to work with TypingLabel effects, which use `{EFFECT=parameters;for;it}`, is going to be more interesting.

**Comment by tommyettinger** [comment]
This should work for all square-bracket markup now. I don't see a good way to have it affect curly-brace effects, yet. You can try this (and some more related features) in https://github.com/tommyettinger/textratypist/releases/tag/v0.10.0 ; note that `[ ]` has replaced the old TextraTypist `[]` and now `[]` should act how it does for BitmapFont.
