### ISSUE TITLE
Label with text "{[" will cause exception

### ISSUE THREAD

**Issue by lucas-kakele** [tommyettinger/textratypist#15]
To reproduce this, create a label like the following:

`new TextraLabel("{[", skin)`

This will cause an exception.

I believe the culprit line is at Font.java:

[`if (enableSquareBrackets && c == '[' && i < end && text.charAt(i + 1) == '+') innerSquareStart = i;`](https://github.com/tommyettinger/textratypist/blob/75eed0290fdb4c44a43298c15e9c606c260b86a3/src/main/java/com/github/tommyettinger/textra/Font.java#L4564)

And the fix could be:

`if (enableSquareBrackets && c == '[' && i + 1 < end && text.charAt(i + 1) == '+') innerSquareStart = i;`

Cheers!

**Comment by tommyettinger** [comment]
Good catch, I'll implement this now.
