### ISSUE TITLE
Fonts with scale are drawn incorrectly

### ISSUE THREAD

**Issue by lucas-viva** [tommyettinger/textratypist#16]
Hello!

The following code (with the extra `invalidateHierarchy` call at `TextraLabel.layout`, from https://github.com/tommyettinger/textratypist/issues/13#issuecomment-1927853865):

```
package com.mygdx.game;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.Stack;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.utils.Align;
import com.badlogic.gdx.utils.ScreenUtils;
import com.badlogic.gdx.utils.viewport.ScreenViewport;
import com.github.tommyettinger.textra.TextraLabel;

public class MyGdxGame extends ApplicationAdapter {

  private Stage stage;
  private Skin skin;

  @Override
  public void create () {
    stage = new Stage(new ScreenViewport());

    skin = new Skin(Gdx.files.internal("uiskin.json"));

    skin.getFont("default-font").getData().setScale(2);

    TextraLabel label = new TextraLabel("This is a test. This is a test. This is a test. This is a test. This is a test.", skin) {
      @Override
      public void layout() {
        float width = getWidth();
        if (style != null && style.background != null) {
          width = (width - (style.background.getLeftWidth() + style.background.getRightWidth()));
        }
        if (wrap && layout.getTargetWidth() != width) {
          if(width != 0)
            layout.setTargetWidth(width);
          font.regenerateLayout(layout);
          invalidateHierarchy(); // Uncomment this line to fix the issue.
        }
      }
    };
    label.setWrap(true);
    label.setAlignment(Align.left);

    Table table = new Table(skin);
    table.setBackground("default-pane");
    table.add(label).prefWidth(300).row();

    Table wrappingTable = new Table();
    wrappingTable.add(table).row();
    wrappingTable.add().growY();

    Stack stack = new Stack(wrappingTable);
    stack.setFillParent(true);

    stage.addActor(stack);
  }

  @Override
  public void render () {
    ScreenUtils.clear(0, 0, 0, 1);
    stage.act();
    stage.draw();
  }

  @Override
  public void dispose () {
    stage.dispose();
    skin.dispose();
  }
}
```

Will result in:

![image](https://github.com/tommyettinger/textratypist/assets/56004737/2b622140-e31d-47a6-8e9a-827b6b628866)

Without setting the font scale, the label is drawn correctly:

![image](https://github.com/tommyettinger/textratypist/assets/56004737/c569dbdc-a683-4cdb-8d2d-17daabfb21a8)

The example above is using libGDX 1.12.2-SNAPSHOT and textralabel 6406d6f093 snapshot.

This also happens to other fonts and also when setting a scale < 1. For example, without scaling:

![image](https://github.com/tommyettinger/textratypist/assets/56004737/f57e27c8-498c-4bbb-9765-5e07e27c2747)

With scale of 0.5f:

![image](https://github.com/tommyettinger/textratypist/assets/56004737/283799de-8230-4986-a783-cb36c0f058d3)

Let me know if you want me to share the second example resources or if you need more details.

Regards.

**Comment by tommyettinger** [comment]
I'll look into this now. The whole mess with when invalidating is good, or expected, or bad, or forbidden, is a mystery to me. Not to mention how invalidate(), invalidateHierarchy(), pack(), layout(), etc. are different...

**Comment by tommyettinger** [comment]
@lucas-kakele You seem to be totally right that invalidateHierarchy() in TextraLabel.layout really helps the line positions. That fix is in now; I may find some other way to make it work, but your fix seems to be the best at this point in time. Once TextraLabels looked more reasonable, I tracked the scale issue to a different area: `new Font(BitmapFont)` currently doesn't handle scaled BitmapFonts very well. You can pass an unscaled BitmapFont to the constructor now, then call `Font.scale(float, float)` or one of the similar methods; this works in the latest code. For scaled BitmapFonts to carry over their scaling to Font, I'll have to dig deeper to figure out what changes in BitmapFont when one of those gets scaled...

**Comment by lucas-kakele** [comment]
Thanks @tommyettinger!

Using an unscaled BitmapFont and then calling Font.scale worked for me.

Regards.

**Comment by tommyettinger** [comment]
OK, almost a year later, but I think this is resolved sufficiently now, heh. I need to clean up old issues more frequently...
