### ISSUE TITLE
Installation/Setup

### ISSUE THREAD

**Issue by 4lfg24** [tommyettinger/textratypist#5]
Hello, sorry but i don't understand well how to include textra typist in my project, could someone be so kind as to explain it in details? Thank you in advance.

**Comment by tommyettinger** [comment]
I guess I'd recommend [gdx-liftoff (link)](https://github.com/tommyettinger/gdx-liftoff/releases/tag/v1.11.0.3) for this; it's an alternative to gdx-setup. You can select TextraTypist as a dependency under `Third-Party`. It would probably help to read [this libGDX wiki article about Gradle dependencies](https://libgdx.com/wiki/articles/dependency-management-with-gradle) if you want to add additional libraries to an existing project. Essentially, the README.md for this project lists the dependencies you need, which is probably just `implementation "com.github.tommyettinger:textratypist:0.6.3"`. That goes in the dependencies section of your core/build.gradle (for gdx-liftoff projects) or the core section of your root build.gradle (for gdx-setup projects). That's the later dependencies block if there is more than one (it doesn't go in the buildscript section).

Any extra stuff would probably involve adding assets. To use the preconfigured fonts in KnownFonts, you need some of the .fnt, .png, and license files from https://github.com/tommyettinger/textratypist/tree/main/knownFonts (just any files you want to use, you don't need all of them). It may be easiest to just download the whole repo as a .zip and get the files that way if you need many. You can also use your own fonts, such as those from a Skin produced by [Skin Composer](https://github.com/raeleus/skin-composer); Skins are pretty important to scene2d.ui usage but they're a little complex, so check the Skin Composer wiki for lots of documentation and instructions for how scene2d.ui works. Generally, if a Skin works in regular scene2d.ui widgets, it probably will work similarly in the widgets here that use TypingLabel or TextraLabel.

If you have more questions, [the libGDX Discord](https://discord.gg/GTmwWD9PR9) can probably walk you through any setup questions you have,
